"""add duplicate_of_id to articles

Revision ID: fb95d856fbf3
Revises: a6d86e112c4f
Create Date: 2026-06-12 21:27:56.573128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb95d856fbf3'
down_revision: Union[str, None] = 'a6d86e112c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('duplicate_of_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'articles', 'articles', ['duplicate_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'duplicate_of_id')
    # ### end Alembic commands ###
